### ISSUE TITLE
Pop up site not working

### ISSUE THREAD

**Issue by lulu4567890** [Hakorr/Userscripts#10]
when i try to open up the A.C.A.S website it will not open it used to work perfectly but not anymore it used to auto open when i start a match but now no matter what i do it refuses to open ive tried running it on different browsers and uninstalling and reinstalling multiple times but still nothing ive been having this issue for 3 days now

**Comment by Hakorr** [comment]
Strange, it works for me, tested both on Brave and Edge browsers.

Are there any error messages on console?

**Comment by lulu4567890** [comment]
no there are no error messages ive used oprea and it worked perfectly before but now will not auto pop up when i start a game and wont open up when i click tamper monkey then open A.C.A.S

**Comment by Hakorr** [comment]
> no there are no error messages ive used oprea and it worked perfectly before but now will not auto pop up when i start a game and wont open up when i click tamper monkey then open A.C.A.S

Attempt using Brave browser and Violentmonkey.
