### ISSUE TITLE
Does not work anymore

### ISSUE THREAD

**Issue by Bluscream** [Hakorr/Userscripts#2]

**Comment by Hakorr** [comment]
Hello, which script are you talking about?

**Comment by Bluscream** [comment]
The aternos one, i just get 3 white boxes in the top left and no text

**Comment by Hakorr** [comment]
The developers are actively checking on new updates and patching them. It should work currently, though. 

I'm using Violentmonkey and Chromium.

**Comment by Bluscream** [comment]
![](https://i.imgur.com/t9N64Ba.png)

**Comment by Hakorr** [comment]
The 2nd method is not really intended to be used currently.

The first one should work just fine, at least on Chrome.

**Comment by Bluscream** [comment]
I currently have a problem that `#UhRKGVxrDuMQoadHLOtKRpIboJEoUHT > div > div` is not being removed


```
userscript.html?name=%5BAternos%5D%20AntiAntiAdblock.user.js&id=1573681e-e2e4-40c8-8d90-a6330db07707:formatted:592 Uncaught TypeError: Cannot read properties of undefined (reading 'parentElement')
    at removeLayer (userscript.html?name=%5BAternos%5D%20AntiAntiAdblock.user.js&id=1573681e-e2e4-40c8-8d90-a6330db07707:formatted:592)
    at eval (userscript.html?name=%5BAternos%5D%20AntiAntiAdblock.user.js&id=1573681e-e2e4-40c8-8d90-a6330db07707:formatted:597)
```

https://github.com/Hakorr/Userscripts/blob/main/Aternos.com/AntiAntiAdblock/userscript.js#L97

**Comment by Hakorr** [comment]
I'll get it fixed soon. I didn't realize you were talking about that element.

**Comment by Bluscream** [comment]
> I'll get it fixed soon. I didn't realize you were talking about that element.

well, the element is forbidding me to click on start server, so it's quite important xD

**Comment by Hakorr** [comment]
Update the script, it's fixed now.

Watch them patch it in 10 minutes.

Edit: Yeah, as expected. I'll come back later, probably.
