### ISSUE TITLE
a.c.a.s

### ISSUE THREAD

**Issue by ExplodingTnt144** [Hakorr/Userscripts#4]
i used acas before and it was working but now its not working anymore on opera gx? how do i fix it

**Comment by Hakorr** [comment]
Hey, can you describe the problem a bit more? Does the GUI open up?

Also, use `CTRL + SHIFT + I` to access the console while on chess.com. Screenshot any errors you see that have the name A.C.A.S on the right side of the error log.

**Comment by ExplodingTnt144** [comment]
The gui doesn't open up and there are no error with a.c.a.s popping up

**Comment by Hakorr** [comment]
Make sure you're using the latest version of Opera GX and A.C.A.S. Use [Violentmonkey](https://violentmonkey.github.io). I just tried it and it works.

**Comment by ExplodingTnt144** [comment]
I reinstalled Violentmonkey the script and my opera gx is up to date and the gui still wont show up

**Comment by Hakorr** [comment]
Have you disabled popups by accident? A.C.A.S should notify you if you haven't enabled popups, but the system is not perfect. Maybe some other extensions are messing with the userscript?

Other than that, I don't know what the issue could be. I can't replicate it, so it's hard to debug and fix. You might need to use a different Chromium browser to use A.C.A.S, or completely reinstall Opera GX.

**Comment by ExplodingTnt144** [comment]
I tried using it on chrome and yes it did notify me about the pop up blocked and it worked like it should have but on opera gx im trying to figure out why it doesn't work anymore

**Comment by Hakorr** [comment]
I'm quite positive the problem is out of my reach. There were some chunky updates to A.C.A.S last day, so if it was caused by those updates, it wouldn't work for me as well, but it did.

Try clearing your cache and other browser data (you can keep bookmarks, cookies and so forth) and attempt again.

**Comment by ExplodingTnt144** [comment]
okay ill try thanks for helping
