### ISSUE TITLE
External Site Not launching

### ISSUE THREAD

**Issue by Lusionary23** [Hakorr/Userscripts#5]

**Comment by Lusionary23** [comment]
Usually the website opens when I press online but it is not doing it no matter what. Even against bots it does not want to launch.

**Comment by Hakorr** [comment]
Just checked, still working for me. Here are some things you can attempt to do,

1. Use a Chromium based browser like Chrome or Brave. Try using Violentmonkey.
2. Reinstall the userscript.
3. Make sure your popups aren't blocked.
4. Use Chess.com's board animation type "*Medium (Default)*"
5. Did you accidentally enable "*Display moves on site*"? Open the GUI manually via your userscript manager. There should be an "Open A.C.A.S" button.

Here are other threads about the same issue,
- [GreasyFork - The script worked once](https://greasyfork.org/en/scripts/459137-a-c-a-s-advanced-chess-assistance-system/discussions/167738)
- #4
