### ISSUE TITLE
resource problems

### ISSUE THREAD

**Issue by ghost** [Hakorr/Userscripts#9]
![image](https://user-images.githubusercontent.com/87625392/229837376-92a1de3c-ed64-46e7-944b-2bb641294853.png)

**Comment by ghost** [comment]
i tried using a proxy like this one : https://science-quizzez.vercel.app/ but it didn't fix it meaning, that the raw github has problems

**Comment by Hakorr** [comment]
Hey, it seems to work for me. Are you still having that issue?

**Comment by ghost** [comment]
Yes i still have the issue

**Comment by ghost** [comment]
Im on a school internet

**Comment by Hakorr** [comment]
> Im on a school internet

Can you please attempt using a different internet connection? I'm quite certain the problem is out of my reach.
